### ISSUE TITLE
Incorrect Password

### ISSUE THREAD

**Issue by scottgreenup** [jaseg/i3lock#4]
Haven't looked much into it, not sure if it happens on other machines. Problem fixed when going back to official i3lock.

When password is incorrect, characters are automatically fed into i3lock-background, exactly n+1 characters.
1. Run i3lock
2. Put in incorrect password, e.g. "a"
3. Hit 'enter'
4. 'Verifying...' ... 'Wrong!' ... then 2 characters are fed from stdin/orsomething

**Comment by jaseg** [comment]
I have not looked at this project for quite some time. I would strongly discourage anyone from using this project or basically any other screen locker except xscreensaver for security reasons. I have put up a warning in the README.md with a link to some explanation by somebody with more experience than myself.
